// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6steelea3.Models;

namespace Mission6steelea3.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230222152535_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission6steelea3.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categories")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Categories = "Horror"
                        },
                        new
                        {
                            CategoryId = 2,
                            Categories = "Action"
                        },
                        new
                        {
                            CategoryId = 3,
                            Categories = "Drama"
                        },
                        new
                        {
                            CategoryId = 4,
                            Categories = "Romance"
                        },
                        new
                        {
                            CategoryId = 5,
                            Categories = "SciFi"
                        },
                        new
                        {
                            CategoryId = 6,
                            Categories = "Comedy"
                        });
                });

            modelBuilder.Entity("Mission6steelea3.Models.MovieFormResponse", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FormId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            FormId = 1,
                            CategoryId = 5,
                            Director = "Christopher Nolan",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            FormId = 2,
                            CategoryId = 4,
                            Director = "Taika Waititi",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "R",
                            Title = "Eagle vs Shark",
                            Year = 2007
                        },
                        new
                        {
                            FormId = 3,
                            CategoryId = 3,
                            Director = "Tyler Nilson, Michael Schwartz",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "The Peanut Butter Falcon",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("Mission6steelea3.Models.MovieFormResponse", b =>
                {
                    b.HasOne("Mission6steelea3.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
